version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  solhint:
    docker:
      - image: circleci/node:10.10-stretch
    steps:
      - checkout
      - run:
          name: "Solhint"
          command: |
            sudo npm install -g solhint@^1.5.1
            cd truffle
            mkdir -p test-results/solhint && solhint ./**/**/*.sol -f junit > test-results/solhint/results.xml
      - store_test_results:
          path: truffle/test-results

  truffle-compile:
    docker:
      - image: circleci/node:10.10-stretch
    steps:
      - checkout
      - run:
          name: "Download solc"
          command: |
            wget https://github.com/ethereum/solidity/releases/download/v0.5.0/solc-static-linux
            chmod +x solc-static-linux
            sudo mv solc-static-linux /usr/bin/solc
      - run:
          name: "Compile Truffle"
          command: |
            cd truffle
            npm install
            npm run truffle -- compile --all --network circleci
      - run:
          name: "Flatten solidity for static analysis"
          command: |
            cd truffle
            npm run flatten
            npm run combine
      - persist_to_workspace:
          root: truffle
          paths:
            - build
            - node_modules
            - flat-sol
            - combined-sol

  mythril:
    docker:
      - image: mythril/myth:0.20.0
    steps:
      - checkout
      - attach_workspace:
          at: truffle
      - run:
          name: "Run Mythril"
          command: |
            cd truffle
            myth --truffle

  truffle-tests:
    docker:
      - image: circleci/node:10.10-stretch
      - image: trufflesuite/ganache-cli:v6.3.0
    steps:
      - checkout
      - attach_workspace:
          at: truffle
      - run:  # Temporary fix for https://github.com/trufflesuite/truffle/issues/469
          name: "Download solc"
          command: |
            wget https://github.com/ethereum/solidity/releases/download/v0.5.0/solc-static-linux
            chmod +x solc-static-linux
            sudo mv solc-static-linux /usr/bin/solc
      - run:
          name: "Truffle Tests"
          command: |
            cd truffle
            npm run truffle -- test --network circleci
      - store_test_results:
          path: truffle/test-results

#  solidity-coverage:  # Disabled due to incompatibility with Truffle 5/Sol 0.5.0
#    docker:
#      - image: circleci/node:10.10-stretch
#    steps:
#      - checkout
#      - attach_workspace:
#          at: truffle
#      - run:
#          name: "Solidity test coverage"
#          command: |
#            cd truffle
#            npm run coverage || true
#      - store_artifacts:
#          path: truffle/coverage

  slither:
    docker:
      - image: shipchain/slither:0.5.2
    steps:
      - checkout
      - attach_workspace:
          at: truffle
      - run:
          name: "Slither analysis"
          command: |
            cd truffle
            mkdir slither || true
            slither . --print inheritance-graph --json slither/output.json || true
            dot -Tpng export.dot > slither/LoadContract.png
      - store_artifacts:
          path: truffle/slither

  securify:
    docker:
      - image: shipchain/securify:aef12a3
    steps:
      - checkout
      - attach_workspace:
          at: truffle
      - run:
          name: "Securify tests"
          command: |
            rm /project/example.sol
            cp -r "$(realpath truffle/flat-sol)/." /project
            rm /project/Migrations.sol
            cd /sec
            python3 docker_run_securify.py -p /project
          no_output_timeout: 30m

  deploy-version:
    docker:
      - image: circleci/node:10.10-stretch
    steps:
      - checkout
      - attach_workspace:
          at: truffle
      - run:
          name: "Install sponge"
          command: |
            sudo apt-get install moreutils
      - run:
          name: "Configure Git"
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git config --global user.email ahodges+shippy@shipchain.io
            git config --global user.name MrShippy

      - run:
          name: "Clone meta-contracts"
          command: |
            git clone git@github.com:shipchain/meta-contracts.git
      - run:
          name: "Update meta-contracts repo with new LOAD version"
          command: |
            export VERSION=$(cat truffle/contracts/Load/VERSION)
            export ABI=$(jq -rc .abi truffle/build/contracts/LoadContract.json)
            export BYTECODE=$(jq -rc .bytecode truffle/build/contracts/LoadContract.json)
            jq -e '.contracts.LOAD.latest != env.VERSION' meta-contracts/meta.json || { echo "Current version of LOAD contract is already deployed"; exit 1; }
            jq -r '.contracts.LOAD.versions[env.VERSION].abi=env.ABI | .contracts.LOAD.versions[env.VERSION].bin=env.BYTECODE | .contracts.LOAD.versions[env.VERSION]["git-hash"]=env.CIRCLE_SHA1 | .contracts.LOAD.latest=env.VERSION' meta-contracts/meta.json | sponge meta-contracts/meta.json
            git -C meta-contracts commit -a -m "Published LOAD $VERSION to meta-contracts"

            export NOTARY_VERSION=$(cat truffle/contracts/VaultNotary/VERSION)
            export ABI=$(jq -rc .abi truffle/build/contracts/VaultNotary.json)
            export BYTECODE=$(jq -rc .bytecode truffle/build/contracts/VaultNotary.json)
            jq -e '.contracts.VaultNotary.latest != env.NOTARY_VERSION' meta-contracts/meta.json || { echo "Current version of VAULT NOTARY contract is already deployed"; exit 1; }
            jq -r '.contracts.VaultNotary.versions[env.NOTARY_VERSION].abi=env.ABI | .contracts.VaultNotary.versions[env.NOTOARY_VERSION].bin=env.BYTECODE | .contracts.VaultNotary.versions[env.NOTARY_VERSION]["git-hash"]=env.CIRCLE_SHA1 | .contracts.VaultNotary.latest=env.NOTARY_VERSION' meta-contracts/meta.json | sponge meta-contracts/meta.json
            git -C meta-contracts commit -a -m "Published VaultNotary $NOTARY_VERSION to meta-contracts"

            git -C meta-contracts push

workflows:
  version: 2
  build-and-test:
    jobs:
      - solhint
      - truffle-compile:
          requires:
            - solhint
      - mythril:
          requires:
            - truffle-compile
      - truffle-tests:
          requires:
            - truffle-compile
#      - solidity-coverage:
#          requires:
#            - truffle-compile
      - slither:
          requires:
            - truffle-compile
      - securify:
          requires:
            - truffle-compile
      - hold-deploy:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - truffle-tests
            - mythril
      - deploy-version:
          filters:
            branches:
              only: master
          requires:
            - hold-deploy
