version: '3.2'

services:
  ganache:
    image: trufflesuite/ganache-cli:v6.3.0
    expose:
      - "8545"

  truffle:
    build:
      context: ../
    stdin_open: true
    tty: true
    extra_hosts:
     - "outside:${HOST_IP}"
    depends_on:
      - ganache
    volumes:
      - ../truffle:/src/truffle:rw
